# Generated by Django 2.2.6 on 2021-05-14 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('bk_biz_name', models.CharField(max_length=64, null=True, verbose_name='业务名称')),
                ('bk_job_id', models.IntegerField(null=True, verbose_name='作业ID')),
                ('ip_list', models.TextField(null=True, verbose_name='主机列表')),
                ('result', models.IntegerField(null=True, verbose_name='作业执行结果')),
                ('log', models.TextField(null=True, verbose_name='作业执行日志')),
                ('status', models.IntegerField(null=True, verbose_name='作业执行状态')),
                ('created', models.DateField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '执行历史',
                'verbose_name_plural': '执行历史',
                'db_table': 'history',
            },
        ),
    ]
