# Generated by Django 2.2.6 on 2021-05-14 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
