# Generated by Django 2.2.6 on 2021-05-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_application', '0002_auto_20210514_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='bk_biz_id',
            field=models.BigIntegerField(max_length=64, null=True, verbose_name='业务id'),
        ),
    ]
